instance_provision: 'spot'
spot_max_price: 0.80
instance_provision_fallback_on_demand: false
region_name:
  - eu-west-1
user_credentials_path: '~/.ssh/scylla-qa-ec2'
instance_type_loader: 'c5.xlarge'
instance_type_monitor: 't3.large'
# manual on creating loader AMI's: see docs/new_loader_ami.md
ami_id_loader: 'scylla-qa-loader-ami-v20-ubuntu22'
ami_id_monitor: 'ubuntu/images/hvm-ssd/ubuntu-jammy-22.04-amd64-server-20231207' # ubuntu/images/hvm-ssd/ubuntu-jammy-22.04-amd64-server-20231207Canonical, Ubuntu, 22.04 LTS, amd64 jammy image build on 2023-12-07

availability_zone: 'a'
root_disk_size_monitor: 50  # GB, remove this field if default disk size should be used
root_disk_size_db: 30  # GB, increase root disk for larger swap (maximum: 16G)
root_disk_size_loader: 30  # GB, Increase loader disk in order to have extra space for a larger swap
loader_swap_size: 10240  #10GB SWAP space
ami_db_scylla_user: 'scyllaadm'
ami_loader_user: 'ubuntu'
ami_monitor_user: 'ubuntu'
aws_instance_profile_name_db: 'qa-scylla-manager-backup-instance-profile'

ami_id_db_scylla: ''
ami_id_db_oracle: ''

use_preinstalled_scylla: true

backup_bucket_backend: 's3'
backup_bucket_location: 'manager-backup-tests-us-east-1'
backup_bucket_region: 'us-east-1'

data_volume_disk_num: 0
data_volume_disk_type: 'gp2'
data_volume_disk_size: 500
data_volume_disk_iops: 10000 # depend on type iops could be 100-16000 for io2|io3 and 3000-16000 for gp3
